docs: standardize
fernando-mc/serverless-finch pull request #163
Opened 2022-03-08 03:06 UTC by mikejpeters

* combine contributing docs
* point release notes to releases

2022-03-08 03:07 UTC, mikejpeters commented
Unfortunately I guess prettier didn't used to run on markdown files, so this commit caused a lot of formatting changes.

The only real changes are removing the manual release notes in favour of linking to the Releases page, and combining and improving the CONTRIBUTING doc.

2022-03-12 07:29 UTC, Shereef requested changes

2022-03-12 07:29 UTC, Shereef commented on README.md
> -
Everything below here is not on the releases page https://github.com/fernando-mc/serverless-finch/releases

There are no release notes for 2.6.0 and below

Should we maybe leave 2.60 and below release notes in the read me and have the link to the releases tab for others ?

2022-03-12 07:45 UTC, Shereef commented
I have pushed my suggestion. if you agree please merge and release.
If you disagree please remove my commit and hard push and let's talk about it.

I am just trying to make it easy for you to do this from your phone if you agree with my suggestion above

2022-03-12 07:46 UTC, Shereef approved these changes

2022-03-12 15:04 UTC, merged