Resolve file name.: custom: ${file(ymls/custom.yml)}
fernando-mc/serverless-finch pull request #77
Opened 2019-03-18 12:21 UTC by thiagoananias

### Background
I'am having problems because i'am using a file reference path... this is just a way of solving... i don't know if it is the best way.

2019-03-19 23:27 UTC, fernando-mc commented
Can you add a bit more information here? Sorry, I'm a little confused on what this is for? You're using a custom yaml file for configuration information and you want that to be supported by this?

2019-04-02 13:40 UTC, thiagoananias commented
The configuration of my Serverless.yml are not all in the same file, the plugin does not work when i divide the configuration in files.

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: dev
  logRetentionInDays: 7
  region: ${self:custom.regions.${self:provider.stage}}
  versionFunctions: false
  timeout: 30
  stackTags:
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    service: ${self:service}
  environment: ${file(ymls/environment.yml)}

custom: ${file(ymls/custom.yml)}
resources:
  Parameters: ${file(ymls/parameters.yml)}
  Conditions: ${file(ymls/conditions.yml)}
  Resources: ${file(ymls/resources.yml)}

2019-04-02 13:41 UTC, thiagoananias commented
Before the serverless initiate i'm customizing the YML files with some other third party informations

2019-04-27 09:32 UTC, dirgapeter commented
from https://serverless.com/framework/docs/providers/aws/guide/plugins/

> Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.

I do suggest to put `this.options = this.serverless.service.custom.client;` inside `_validateConfig` and initialize with `{}` in constructor.

2020-03-27 19:29 UTC, jodanher commented
> from https://serverless.com/framework/docs/providers/aws/guide/plugins/
> 
> > Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.
> 
> I do suggest to put `this.options = this.serverless.service.custom.client;` inside `_validateConfig` and initialize with `{}` in constructor.

This is a better solution!

2022-02-26 09:40 UTC, Shereef requested changes

2022-02-26 09:40 UTC, Shereef commented on index.js
> +	  this.options = this.serverless.service.custom.client;
Please help us evaluate the issue and your fix by doing the following:

- Rebase off of master
- Format this file so this line is aligned well
- Test with serverless 3
- provide us with a repo that has the minimal code to reproduce this issue 

I realize this is a very old PR and may not be needed anymore so please help us validate that by doing the above steps

2022-03-07 21:24 UTC, closed without merging